// Sri Lanka National Immunization Schedule - Vaccine Data
export const sriLankaVaccineSchedule = [
  {
    vaccineId: 'vaccine_bcg',
    name: 'BCG',
    manufacturer: 'Serum Institute of India / Multiple',
    dosageInfo: 'Single dose',
    recommendedAge: 0,
    intervalDays: 0,
    description:
      'Preferably within 24 hours of birth (Before leaving hospital). If a scar is not present, 2nd dose could be offered after 6 months, up to 5 years.',
    isActive: true,
    notes: '0-4 Weeks',
  },
  {
    vaccineId: 'vaccine_opv1',
    name: 'OPV (1st dose)',
    manufacturer: 'WHO',
    dosageInfo: '2 drops orally',
    recommendedAge: 2,
    intervalDays: 60,
    description: 'Oral Polio Vaccine - 1st dose.',
    isActive: true,
    notes: '2 Months',
  },
  {
    vaccineId: 'vaccine_pentavalent1',
    name: 'Pentavalent - DTP-HepB-Hib (1st dose)',
    manufacturer: 'Serum Institute of India',
    dosageInfo: '0.5 ml injection',
    recommendedAge: 2,
    intervalDays: 60,
    description:
      'Combined vaccine for Diphtheria, Pertussis, Tetanus, Hepatitis B, and Haemophilus influenzae type b.',
    isActive: true,
    notes: '2 Months',
  },
  {
    vaccineId: 'vaccine_fipv1',
    name: 'fIPV - Fractional IPV (1st dose)',
    manufacturer: 'WHO',
    dosageInfo: 'Fractional dose',
    recommendedAge: 2,
    intervalDays: 60,
    description: 'Inactivated Polio Vaccine - Fractional dose.',
    isActive: true,
    notes: '2 Months',
  },
  {
    vaccineId: 'vaccine_opv2',
    name: 'OPV (2nd dose)',
    manufacturer: 'WHO',
    dosageInfo: '2 drops orally',
    recommendedAge: 4,
    intervalDays: 60,
    description: 'Oral Polio Vaccine - 2nd dose.',
    isActive: true,
    notes: '4 Months',
  },
  {
    vaccineId: 'vaccine_pentavalent2',
    name: 'Pentavalent - DTP-HepB-Hib (2nd dose)',
    manufacturer: 'Serum Institute of India',
    dosageInfo: '0.5 ml injection',
    recommendedAge: 4,
    intervalDays: 60,
    description: 'Combined vaccine - 2nd dose.',
    isActive: true,
    notes: '4 Months',
  },
  {
    vaccineId: 'vaccine_fipv2',
    name: 'fIPV - Fractional IPV (2nd dose)',
    manufacturer: 'WHO',
    dosageInfo: 'Fractional dose',
    recommendedAge: 4,
    intervalDays: 60,
    description: 'Inactivated Polio Vaccine - Fractional dose.',
    isActive: true,
    notes: '4 Months',
  },
  {
    vaccineId: 'vaccine_pentavalent3',
    name: 'Pentavalent - DTP-HepB-Hib (3rd dose)',
    manufacturer: 'Serum Institute of India',
    dosageInfo: '0.5 ml injection',
    recommendedAge: 6,
    intervalDays: 60,
    description: 'Combined vaccine - 3rd dose.',
    isActive: true,
    notes: '6 Months',
  },
  {
    vaccineId: 'vaccine_mmr1',
    name: 'MMR (1st Dose)',
    manufacturer: 'Serum Institute of India',
    dosageInfo: '0.5 ml injection',
    recommendedAge: 9,
    intervalDays: 90,
    description: 'Measles, Mumps, Rubella - 1st dose.',
    isActive: true,
    notes: '9 Months',
  },
  {
    vaccineId: 'vaccine_je',
    name: 'Live JE',
    manufacturer: 'Serum Institute of India',
    dosageInfo: '0.5 ml injection',
    recommendedAge: 12,
    intervalDays: 90,
    description: 'Japanese Encephalitis vaccine.',
    isActive: true,
    notes: '12 months',
  },
  {
    vaccineId: 'vaccine_opv4',
    name: 'OPV & DTP (4th dose)',
    manufacturer: 'WHO / Serum Institute',
    dosageInfo: 'Combination injection',
    recommendedAge: 18,
    intervalDays: 180,
    description: 'OPV and DTP booster.',
    isActive: true,
    notes: '18 months',
  },
  {
    vaccineId: 'vaccine_mmr2',
    name: 'MMR (2nd Dose)',
    manufacturer: 'Serum Institute of India',
    dosageInfo: '0.5 ml injection',
    recommendedAge: 36,
    intervalDays: 1080,
    description: 'Measles, Mumps, Rubella - 2nd dose.',
    isActive: true,
    notes: '3 years',
  },
  {
    vaccineId: 'vaccine_dpt5',
    name: 'OPV & DT (5th dose)',
    manufacturer: 'WHO / Serum Institute',
    dosageInfo: 'Combination injection',
    recommendedAge: 60,
    intervalDays: 1440,
    description: 'OPV and DT booster.',
    isActive: true,
    notes: '5 years',
  },
  {
    vaccineId: 'vaccine_hpv1',
    name: 'HPV (1st Dose)',
    manufacturer: 'Merck / GSK',
    dosageInfo: '0.5 ml injection',
    recommendedAge: 120,
    intervalDays: 0,
    description: 'Human Papillomavirus vaccine - 1st dose.',
    isActive: true,
    notes: '10 years (Grade 6)',
  },
  {
    vaccineId: 'vaccine_hpv2',
    name: 'HPV (2nd Dose)',
    manufacturer: 'Merck / GSK',
    dosageInfo: '0.5 ml injection',
    recommendedAge: 120,
    intervalDays: 180,
    description: 'Human Papillomavirus vaccine - 2nd dose.',
    isActive: true,
    notes: '6 months after 1st dose',
  },
  {
    vaccineId: 'vaccine_atd',
    name: 'aTd (adult Tetanus diphtheria)',
    manufacturer: 'Serum Institute of India',
    dosageInfo: '0.5 ml injection',
    recommendedAge: 132,
    intervalDays: 360,
    description: 'Adult Tetanus and Diphtheria booster.',
    isActive: true,
    notes: '11 years',
  },
];

export type VaccineScheduleEntry = (typeof sriLankaVaccineSchedule)[0];

